### PR TITLE
Fix SPM compilation

### PR DESCRIPTION
**Pull request by vmanot**
Fixes #82, building upon #26.

You would not _believe_ the number of hacks I went through to get this to work.

### Implementation
- Create a new module `ProtonCore` - to be consumed by `Proton` (still a single package though) 
- Move Objective-C files to `ProtonCore` 
- Add interfaces to the the ObjC files to allow it to work with with `Proton`'s ObjC declarations. 
- Modify `Proton` to cast wherever appropriate.

### CODE REVIEW

**Comment by rajdeep** [comment]
@vmanot, it seems that the files have not been correctly referenced in the Project. The build is failing for the same reason: https://github.com/rajdeep/proton/pull/82/checks

This is what I see on local machine:
project-ref

**Comment by YoX89** [comment]
I see the same as @rajdeep. I tried to manually fix the reference issues but it wasn't enough it seems. Importing this branch as a Swift Package works but building it locally doesn't. 

The reason is that the local project needs to have the ProtonCore framework as well. Otherwise the `import ProtonCore` statements won't compile, which makes sense because ProtonCore only exists in SPM. So I think the solution is to first fix the references and then create a ProtonCore framework that mirrors the SPM ProtonCore target.

**Comment by rajdeep** [comment]
Superseded by #110. Thanks for your efforts and input, @vmanot

**Comment by rajdeep** [comment]
@YoX89 the changes were beyond just fixing the references as over time there was cyclic dependency created between ObjC and Swift code. Since ObjC code now needed it's own module, I had to change bits to break the dependency of ObjC code on Swift. You should be able to try the latest branch for `spm-support` with SPM.

**Pull request closed without merging**
